<script>
    var ajaxUrl = "<?php echo Mage::helper("adminhtml")->getUrl("adminhtml/trustpilot/ajax"); ?>";
</script>
<script type="text/javascript">
    function onTrustpilotIframeLoad() {
        if (typeof sendSettings === "function" && typeof sendPastOrdersInfo === "function") {
            sendSettings();
            sendPastOrdersInfo();
        } else {
            window.addEventListener('load', function () {
                sendSettings();
                sendPastOrdersInfo();
            });
        }
    }
</script>
<div class='wrap' tabindex="0">
    <iframe
        src='<?php echo $this->data['IntegrationAppUrl']; ?>'
        id='configuration_iframe'
        frameborder='0'
        scrolling='no'
        width='100%'
        height='1400px'
        data-plugin-version='<?php echo Trustpilot_Reviews_Model_Config::TRUSTPILOT_PLUGIN_VERSION ?>'
        data-source='Magento1'
        data-version='<?php echo 'Magento1-'. Mage::getVersion() ?>'
        data-page-urls='<?php echo $this->data['PageUrls']; ?>'
        data-transfer='<?php echo $this->data['IntegrationAppUrl']; ?>'
        data-past-orders='<?php echo $this->data['PastOrdersInfo']; ?>'
        data-settings='<?php echo $this->data['Settings']; ?>'
        data-product-identification-options = '<?php echo $this->data['ProductIdentificationOptions']; ?>'
        data-configuration-scope-tree = '<?php echo $this->data['ConfigurationScopeTree']; ?>'
        data-is-from-marketplace = '<?php echo Trustpilot_Reviews_Model_Config::TRUSTPILOT_IS_FROM_MARKETPLACE ?>'
        data-plugin-status = '<?php echo $this->data['PluginStatus']; ?>'
        onload='onTrustpilotIframeLoad();'>
    </iframe>
    <div id='trustpilot-trustbox-preview'
        hidden='true'
        data-page-urls='<?php echo $this->data['PageUrls']; ?>'
        data-custom-trustboxes='<?php echo $this->data['CustomTrustboxes']; ?>'
        data-settings='<?php echo $this->data['Settings']; ?>'
        data-source='Magento1'
        data-sku='<?php echo $this->data['Sku'] ?>'
        data-name='<?php echo $this->data['ProductName']; ?>'
    >
    </div>
    <script src='<?php echo Trustpilot_Reviews_Model_Config::TRUSTPILOT_TRUSTBOX_PREVIEW_URL ?>' id='TrustBoxPreviewComponent'></script>
</div>
